name: html2md
description: Convert html to markdown in Dart.
version: 1.2.3
homepage: https://github.com/jarontai/html2md
publish_to: https://pub.dev/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: ^0.15.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.5
