name: html2md
description: Convert html to markdown in Dart.
version: 0.1.6
homepage: https://github.com/jarontai/html2md
authors:
  - jarontai <jaroncn@gmail.com>
  - Tadej Kanižar

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  html: "^0.13.3"

dev_dependencies:
  test: ^0.12.0
