name: html2md
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: jarontai <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  html: "^0.13.3"

dev_dependencies:
  test: ^0.12.0
